//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ApiFileUpload.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserContact
    {
        public int UserID { get; set; }
        public string UserName { get; set; }
        public string Contact { get; set; }
        public string Avatar { get; set; }
        public string Signature { get; set; }
    }
}
